# Config

export EDITOR="vim"
export GOKU_EDN_CONFIG_FILE="/Users/ccblaisdell/dev/dotfiles/karabiner.edn"
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# asdf
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
# append completions to fpath
fpath=(${ASDF_DATA_DIR:-$HOME/.asdf}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

# My aliases
source $HOME/.zsh_aliases
[ -f ~/.work/.zshrc ] && source ~/.work/.zshrc

# Press V to enter Vi mode
bindkey -v

# Z
. /opt/homebrew/etc/profile.d/z.sh

# native zsh autocomplete
autoload -Uz compinit && compinit

# Fish-like autosuggestions
# https://github.com/zsh-users/zsh-autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Make autosuggest colors look nicer in tmux
# https://github.com/zsh-users/zsh-autosuggestions/issues/229#issuecomment-300675586
export TERM=xterm-256color

# Falcon CLI Autosuggest. Generated by `falcon completion zsh`
# https://git.soma.salesforce.com/pages/sfdc-falcon/cli/#autocompletion
[ -f ~/.work/falcon-completion.sh ] && source ~/.work/falcon-completion.sh

# Set Bat's theme
export BAT_THEME="Nord"

# Direnv hook
eval "$(direnv hook zsh)"

# Probably needs to be last(-ish)
eval "$(starship init zsh)"

export PATH="/usr/local/sbin:/Users/ccblaisdell/.cargo/bin:$PATH"

ssh-add --apple-load-keychain

# Ctrl+R to fuzzy search command history
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Added by dx-cli for Claude Code (native binary installation)
export PATH="$HOME/.local/bin:$PATH"

# Added by dx-cli for Claude Code CA certificates
export NODE_EXTRA_CA_CERTS="/Users/ccblaisdell/.claude/certs/salesforce-ca-bundle.pem"

# >>> aisuite >>>
[ -f "/Users/ccblaisdell/.aisuite/env.sh" ] && source "/Users/ccblaisdell/.aisuite/env.sh"
# <<< aisuite <<<
