# Main Brewfile - combines core and personal packages
instance_eval(File.read(File.expand_path("~/.dotfiles/Brewfile-core")))
instance_eval(File.read(File.expand_path("~/.dotfiles/Brewfile-personal")))
